export const NATS_JETSTREAM_OPTIONS = Symbol("NATS_JETSTREAM_OPTIONS");
export const NATS_MESSAGE_HANDLER = Symbol("NATS_MESSAGE_HANDLER");
export const NATS_SERVICE = Symbol("NATS_SERVICE");

export const NATS_JETSTREAM_CLIENT = Symbol("NATS_JETSTREAM_CLIENT");
